blank_issues_enabled: false
contact_links:
  - name: Go to Reden
    url: https://github.com/zly2006/reden-is-wjat-we-made
    about: This mod is hard forked from Reden Mod, and it is not officially supported by Reden Mod maintainers.
  - name: Join Discord Server
    url: https://discord.gg/jUUPjgyAz5
    about: Ask questions and discuss with Reden Mod maintainers and community
